### PR TITLE
responsiveness added

### PR DESCRIPTION
**Pull request by Alarlar**

### CODE REVIEW

**Comment by brandaogabriel7** [comment]
Hi Dinar!

As I told you via Slack, I'll review 3 of your assignments (10, 11, and 12) in this pull request as the other ones were already merged. I'll leave one comment for each assignment containing its checklist and any suggestions I have.

I'm using your main branch as a reference.

**Comment by brandaogabriel7** [comment]
## Lesson 10 - CSS Basics
Your CSS file looks good overall and applies many CSS concepts and features. The issue is that those styles are not currently working. Your stylesheet import is incorrect and some of the selectors you tried using don't match the elements defined in your HTML.

Below, I used the assignment checklists to indicate the requirements you fulfilled and to leave comments on what needs to be revised.

### Create and Load Stylesheet
- [x] Create a folder called css at the same level as your README.md and index.html files
  > You named this folder `CSS` instead of `css`, which is not the usual, but it is not wrong.
- [x] Inside that folder, create a Cascading Style Sheets (CSS) file called index.css
- [x] Open your index.html file
- [ ] Before the closing </head> tag, insert a <link> element with a rel attribute of "stylesheet" and an href attribute that specifies the relative path to your CSS file (i.e. css/index.css)
  > You forgot to use the relative path here. Your `link` tag looks like this:
  > `<link rel="stylesheet" href="index.css" />`
  > which does not correctly import the stylesheet, you're missing the folder in your path. It should be:
  > `<link rel="stylesheet" href="CSS/index.css" />`
### Write CSS
**Important:** Since your stylesheet import is not using the right path, your CSS changes are not being applied. Nonetheless, I still marked the requirements that would be fulfilled by the current stylesheet.
- [x] Change the background color of the page body
- [ ] Change the default text color
  > You only changed the text color for links and nav items. To change the default text color for the whole page, you can set it in the body styles.
- [x] Customize the font family
  - [ ] STRETCH GOAL (optional): load in a font family from [Google Fonts](https://fonts.google.com/)
- [x] Add spacing (padding/margin) between sections
- [ ] Change the alignment of the content of one of your sections
  > You're changing the alignment for the `.name` class, which doesn't match any elements in your HTML.
- [ ] Change the font size, weight, and color of headings
- [ ] Transform the style of your Name at the top of the page
  - [ ] STRETCH GOAL (optional): add a picture of yourself to HTML and/or CSS (remember to include accessibility aspects if you add any images!)
- [ ] Transform the "Experience" list items into styled blocks
  > Those are styled differently because of the `a` selectors you used, but the styles added to the `.experience-container` and `.experience-item` do not work because those don't match any elements in your HTML.
- [ ] Transform the style of the "Connect" links
  > These links are also styled because of the styles added with the `a` selector, but the class `.connect-list` doesn't match anything in your HTML, either.
  - [ ] STRETCH GOAL (optional): make or use social media icons to replace your link text with images

**Comment by Alarlar** [comment]
Hi, thank you!On Apr 18, 2024, at 12:45 PM, Gabriel Silva Brandão ***@***.***> wrote:﻿
Lesson 10 - CSS Basics
Your CSS file looks good overall and applies many CSS concepts and features. The issue is that those styles are not currently working. Your stylesheet import is incorrect and some of the selectors you tried using don't match the elements defined in your HTML.
Below, I used the assignment checklists to indicate the requirements you fulfilled and to leave comments on what needs to be revised.
Create and Load Stylesheet

 Create a folder called css at the same level as your README.md and index.html files

You named this folder CSS instead of css, which is not the usual, but it is not wrong.


 Inside that folder, create a Cascading Style Sheets (CSS) file called index.css
 Open your index.html file
 Before the closing  tag, insert a  element with a rel attribute of "stylesheet" and an href attribute that specifies the relative path to your CSS file (i.e. css/index.css)

You forgot to use the relative path here. Your link tag looks like this:
<link rel="stylesheet" href="index.css" />
which does not correctly import the stylesheet, you're missing the folder in your path. It should be:
<link rel="stylesheet" href="CSS/index.css" />



Write CSS
Important: Since your stylesheet import is not using the right path, your CSS changes are not being applied. Nonetheless, I still marked the requirements that would be fulfilled by the current stylesheet.

 Change the background color of the page body
 Change the default text color

You only changed the text color for links and nav items. To change the default text color for the whole page, you can set it in the body styles.


 Customize the font family

 STRETCH GOAL (optional): load in a font family from Google Fonts


 Add spacing (padding/margin) between sections
 Change the alignment of the content of one of your sections

You're changing the alignment for the .name class, which doesn't match any elements in your HTML.


 Change the font size, weight, and color of headings
 Transform the style of your Name at the top of the page

 STRETCH GOAL (optional): add a picture of yourself to HTML and/or CSS (remember to include accessibility aspects if you add any images!)


 Transform the "Experience" list items into styled blocks

Those are styled differently because of the a selectors you used, but the styles added to the .experience-container and .experience-item do not work because those don't match any elements in your HTML.


 Transform the style of the "Connect" links

These links are also styled because of the styles added with the a selector, but the class .connect-list doesn't match anything in your HTML, either.


 STRETCH GOAL (optional): make or use social media icons to replace your link text with images

**Comment by Alarlar** [comment]
> Hi Dinar!
> 
> As I told you via Slack, I'll review 3 of your assignments (10, 11, and 12) in this pull request as the other ones were already merged. I'll leave one comment for each assignment containing its checklist and any suggestions I have.
> 
> I'm using your main branch as a reference.

Thank you.

**Comment by Alarlar** [comment]
I've made the corrections. Thanks for your help. Now I don't understand how to send it out.)

**Pull request merged**
